---
name: "_build"
on:
  - "workflow_call"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:

      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Go"
        uses: "actions/setup-go@v4"
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: "Build artifacts"
        run: "make build_all"

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: "cutefetch"
          path: |
            cutefetch-linux-amd64
            cutefetch-linux-arm64
            cutefetch-darwin-amd64
            cutefetch-darwin-arm64
...
