---
name: "Build"
on:
  - "workflow_call"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    steps:

      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Go"
        uses: "actions/setup-go@v4"
        with:
          go-version-file: 'go.mod'

      - name: "Prepare"
        run: "go mod tidy"

      - name: "Build artifacts"
        run: "go build -v ./..."
...
