---
name: "_lint"
on:
  - "workflow_call"

permissions:
  contents: "read"

jobs:
  go-lint:
    name: "golangci-lint"
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Go"
        uses: "actions/setup-go@v4"
        with:
          go-version-file: "go.mod"
          cache: false

      - name: "Vet"
        run: "go vet ./..."

      - name: "golangci-lint"
        uses: "golangci/golangci-lint-action@v3"
        with:
          version: "v1.54"
...
