---
name: "_lint"
on:
  - "workflow_call"

permissions:
  contents: "read"

jobs:

  make-lint:
    name: "make-lint"
    runs-on: "ubuntu-latest"

    steps:

      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Go"
        uses: "actions/setup-go@v4"
        with:
          go-version-file: "go.mod"
          cache: false

      - name: "make lint"
        run: "make lint"

  golangci-lint:
    name: "golangci-lint"
    runs-on: "ubuntu-latest"

    steps:

      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Go"
        uses: "actions/setup-go@v4"
        with:
          go-version-file: "go.mod"
          cache: false

      - name: "golangci-lint"
        uses: "golangci/golangci-lint-action@v3"
        with:
          version: "v1.55"
...
