---
name: "_test"
on:
  - "workflow_call"

permissions:
  contents: "read"

jobs:
  make-test:
    name: "make-test"
    runs-on: "ubuntu-latest"

    steps:

      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Go"
        uses: "actions/setup-go@v4"
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: "Run tests"
        run: "make test"
...
