---
  name: "Test"
  on:
    - "push"

  jobs:
    build:
      runs-on: "ubuntu-latest"
      strategy:
        matrix:
          go-version: [ '1.19', '1.20', '1.21.x' ]

      steps:

        - name: "Checkout"
          uses: "actions/checkout@v4"

        - name: "Setup Go"
          uses: "actions/setup-go@v4"
          with:
            go-version: "${{ matrix.go-version }}"

        - name: "Prepare"
            run: "go mod tidy"

        - name: "Run tests"
          run: "go test -v ./..."
...
